---
- hosts: Apps
  tasks:
  - name: Allow everything and enable UFW
    ufw:
      state: enabled
      policy: allow

  - name: Set logging
    ufw:
      logging: on

  - name : Allow ssh
    ufw:
      rule: allow
      name: OpenSSH

  - name: Allow all access to tcp port 80
    ufw:
      rule: allow
      port: 80
      proto: tcp

  - name: Allow all access to tcp port 8081
    ufw:
      rule: allow
      port: 8081
      proto: tcp