---
- hosts: Apps
  tasks:
    - name: Synchronize Code
      become: true
      synchronize:
        archive: yes
        compress: yes
        src: ~/source/fast-api-test
        dest: ~/deploy/
        rsync_opts:
        - "--exclude=.git"
      register: sync

    - name: Deploy APP
      become: true
      command: cd ~/source/fast-api-test && docker-compose up --build -d