---
- hosts: Apps
  tasks:
    - name: Synchronize Code
      become: true
      synchronize:
        archive: yes
        compress: yes
        src: /source/helloword
        dest: /test/helloword
      delegate_to: Apps
      register: sync